# Generated by Django 6.0.3 on 2026-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AB', 'AVAILABLE'), ('UR', 'UNDER REPAIR'), ('DS', 'DISCONTINUED')], default='AB', max_length=30),
        ),
    ]
