# Generated by Django 6.0.4 on 2026-04-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('TOYOTA', 'Toyota'), ('VOLKSWAGEN', 'Volkswagen'), ('FORD', 'Ford'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('AUDI', 'Audi'), ('OPEL', 'Opel'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('RENAULT', 'Renault')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('COMPACT', 'Compact'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'Van'), ('LUXURY', 'Luxury'), ('SPORTS', 'Sports Car'), ('ELECTRIC', 'Electric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('COROLLA', 'Corolla'), ('GOLF', 'Golf'), ('ASTRA', 'Astra'), ('FOCUS', 'Focus'), ('3SERIES', '3 Series'), ('A4', 'A4'), ('SPORTAGE', 'Sportage'), ('TUCSON', 'Tucson'), ('MEGANE', 'Megane'), ('C-CLASS', 'C-Class')], max_length=100),
        ),
    ]
